name: CI

on:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Restore nuget packages
      run: nuget restore src/NBAStats.sln
